export const countries = [
  { value: 'FR', label: 'France' },
  { value: 'BE', label: 'Belgique' },
  { value: 'CH', label: 'Suisse' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'DE', label: 'Allemagne' },
  { value: 'ES', label: 'Espagne' },
  { value: 'IT', label: 'Italie' },
  { value: 'PT', label: 'Portugal' },
  { value: 'NL', label: 'Pays-Bas' },
  { value: 'GB', label: 'Royaume-Uni' },
  { value: 'IE', label: 'Irlande' },
  { value: 'AT', label: 'Autriche' },
  { value: 'DK', label: 'Danemark' },
  { value: 'SE', label: 'Suède' },
  { value: 'NO', label: 'Norvège' },
  { value: 'FI', label: 'Finlande' },
  { value: 'PL', label: 'Pologne' },
  { value: 'CZ', label: 'République Tchèque' },
  { value: 'HU', label: 'Hongrie' },
  { value: 'RO', label: 'Roumanie' },
  { value: 'BG', label: 'Bulgarie' },
  { value: 'GR', label: 'Grèce' },
  { value: 'HR', label: 'Croatie' },
  { value: 'SK', label: 'Slovaquie' },
  { value: 'SI', label: 'Slovénie' },
  { value: 'EE', label: 'Estonie' },
  { value: 'LV', label: 'Lettonie' },
  { value: 'LT', label: 'Lituanie' },
  { value: 'MT', label: 'Malte' },
  { value: 'CY', label: 'Chypre' },
  { value: 'US', label: 'États-Unis' },
  { value: 'CA', label: 'Canada' },
  { value: 'AU', label: 'Australie' },
  { value: 'NZ', label: 'Nouvelle-Zélande' },
  { value: 'JP', label: 'Japon' },
  { value: 'CN', label: 'Chine' },
  { value: 'KR', label: 'Corée du Sud' },
  { value: 'IN', label: 'Inde' },
  { value: 'BR', label: 'Brésil' },
  { value: 'MX', label: 'Mexique' },
  { value: 'AR', label: 'Argentine' },
  { value: 'CL', label: 'Chili' },
  { value: 'CO', label: 'Colombie' },
  { value: 'PE', label: 'Pérou' },
  { value: 'ZA', label: 'Afrique du Sud' },
  { value: 'EG', label: 'Égypte' },
  { value: 'MA', label: 'Maroc' },
  { value: 'TN', label: 'Tunisie' },
  { value: 'DZ', label: 'Algérie' },
  { value: 'NG', label: 'Nigéria' },
  { value: 'KE', label: 'Kenya' },
  { value: 'AE', label: 'Émirats Arabes Unis' },
  { value: 'SA', label: 'Arabie Saoudite' },
  { value: 'IL', label: 'Israël' },
  { value: 'TR', label: 'Turquie' },
  { value: 'RU', label: 'Russie' },
  { value: 'UA', label: 'Ukraine' },
];
